### ISSUE TITLE
Error only including luwra

### ISSUE THREAD

**Issue by PicosePablo** [vapourismo/luwra#10]
There is an error when I include luwra.hpp, a lot of errors, this because of the use "interface" Macro u have in the pushable.hpp (i.e) or in others, check it pls :D

**Comment by PicosePablo** [comment]
I solved it adding #undef interface to the luwra.hpp, it seems that Standar C has a f*cking macro....

**Comment by vapourismo** [comment]
What? Could you elaborate?

**Comment by vapourismo** [comment]
I have tested in Windows but only with standard compliant compilers.
