### ISSUE TITLE
LUWRA_WRAP : passing a std::function or lambda

### ISSUE THREAD

**Issue by PicosePablo** [vapourismo/luwra#11]
Hi!,
Is there any way of form in your library to generate a lua_Function via "std::function" or "lambda"?

Nice job!!!!

**Comment by vapourismo** [comment]
You can't use `LUWRA_WRAP` to do this. It only exists to transform arbitrary C functions to `lua_CFunction`s.

It's not possible to push `std::function`s, yet. I am very surprised that this is the case.
Let me see if I can produce something this weekend.

**Comment by vapourismo** [comment]
I've pushed something to branch [pushable-std-functions](https://github.com/vapourismo/luwra/tree/pushable-std-functions).
Can you check and see if that works for you?

**Comment by PicosePablo** [comment]
I will download this new version and give you feedback asap!
Really thx for your quickly work!!!!
