### ISSUE TITLE
Question: macro that captures the function to register in lua

### ISSUE THREAD

**Issue by PicosePablo** [vapourismo/luwra#12]
Hi again, I was googling without answer,
Is there any macro (like unreal or unity do) to capture the function and his parameters? 
Something like this:
`#define LUA_FUNC something`
To do things like that:
`
class Foo {
   LUA_FUNC
      int func(int, char, void*);
}
`
The objective of this is to use it to auto create the function in the lua_state via std::function or something else.
Maybe something similar or any idea??
thx

**Comment by vapourismo** [comment]
It is not clear to me what you're trying to achieve here. I'll answer what I think is the question.

The problem with class methods is that the corresponding Lua function `func` needs to accept an instance of `Foo` as the first parameter.

Refer to the documentation on [class members](http://luwra.vprsm.de/wrapping/#class-members) and  [user types](http://luwra.vprsm.de/usertypes/).

Also see the [LUWRA_WRAP_MEMBER](http://luwra.vprsm.de/reference/wrappers_8hpp.html#a92d5de05f0a57a27b6e0601c6720585b) macro.

You would use this as follows.

```c++
lua_CFunction fooFunc = LUWRA_WRAP_MEMBER(Foo, func);

// or when func is not inherited:
lua_CFunction fooFunc = LUWRA_WRAP(Foo::func);

// Set it as a global function for instance
luwra::setGlobal(lua, "foo_func", fooFunc);
```

In Lua you would call it like this:
```lua
-- 'foo' is a userdata pointing to an instance of 'Foo'
foo_func(foo, 1337, "Hello World", some_pointer)
```

These wrappers essentially turn the C++ methods into Lua functions that accept an instance of the class they belong to as the first parameter.

**Comment by PicosePablo** [comment]
It is not exactly what I refer, but I can do something with that. Thank you
Another simple question, when you call:
`luwra::getGlobal<T>(lua, "name")`
is there any form to check if the "name" is in the global value? Program breaks if this name does not exist, maybe something similar to this supposed function:
`
int value = 0;
int result = luwra::getGlobal<int>(lua, "name", &value);
if(!result){
  //do something
}
`

**Comment by vapourismo** [comment]
Perhaps you could explain it better, I might be able to help you.

I don't think Lua allows you to check whether a table contains a given field. The way this works in Lua is to read the field and check if what you got is `nil` or not. A work around would be to specialize the `Value` template to support things like `std::optional`.

**Comment by PicosePablo** [comment]
I will try,
Lua allows you to check when an error occurs via lua_get error, if you try to get something from the global table, if does not exists, it insert an error string in the table, so, when you call 
`luwra::getGlobal<int>(lua, "name", &value);`
it assumes that this variable exists, and if not, obviously, the program calls to the segmentation fault (cause it returns `nil`)
Is it not posible? Check whether you try to access to an undefined name in the table and catch the error?

**Comment by vapourismo** [comment]
The function doesn't segfault. It will indirectly call the Lua error handler. The error here is encountering `nil` instead of the expected type. This is encountered inside the Lua VM, not on Luwra's side.

This means that the solution I described previously is the way to go.
