### ISSUE TITLE
Iterating over a table

### ISSUE THREAD

**Issue by alekseyt** [vapourismo/luwra#14]
This is rather a question.

I have Lua table like this:

```lua
{
  { key1 = value1, key2 = value2 },
  { key3 = value3, key3 = value2 },
}
```

C++:

```c++
const luwra::Table table = luwra::read(L, -1);
```

I want to iterate over it in C++ but i don't see how i can do that. There is `operator[]` and `get()`, but how do i know how many elements in the table?

I've made the following patch to work this around:

```diff
--- a/3rdparty/luwra/lib/luwra/types/table.hpp
+++ b/3rdparty/luwra/lib/luwra/types/table.hpp
@@ -241,6 +241,17 @@ struct Table {
                lua_pop(state, 2);
                return ret;
        }
+
+       inline size_t size() const {
+               State* state = ref.life->state;
+
+               push(state, ref);
+
+               const size_t len = lua_rawlen(state, -1);
+
+               lua_pop(state, 1);
+               return len;
+       }
 };
 
 /// Enables reading/pushing tables
```

It adds `size_t Table::size()`.

What am i missing? Or would you accept pull request like this?

I'm using Lua 5.3 and mot sure how well this will play with Lua 5.2 or 5.1. Or maybe `luwra::size()` would be better?

Related question i have is how to iterate on a table like this:

```lua
{
  key1 = value1,
  key2 = value2,
  key3 = value3,
}
```

With patch above i know size of the table, but i don't know keys. I worked this around by introducing list of keys i want to read, but maybe there is a way to get all available table keys?

**Comment by alekseyt** [comment]
Here is another variant that seems to solve both problems in #14 and #15.

```c++
--- a/3rdparty/luwra/lib/luwra/types/table.hpp
+++ b/3rdparty/luwra/lib/luwra/types/table.hpp
@@ -12,6 +12,7 @@
 #include "../stack.hpp"
 #include "reference.hpp"
 
+#include <functional>
 #include <utility>
 
 LUWRA_NS_BEGIN
@@ -241,6 +242,35 @@ struct Table {
                lua_pop(state, 2);
                return ret;
        }
+
+       template <typename Key>
+       using ForEachCallback = std::function<bool(State* state, const Key& key, int value_index)>;
+
+       template <typename Key>
+       void forEach(ForEachCallback<Key> callback) const {
+               State* state = ref.life->state;
+
+               // https://stackoverflow.com/questions/6137684/iterate-through-lua-table
+
+               push(state, ref); // stack: -1 => table
+
+               lua_pushnil(state);
+               while (lua_next(state, -2)) { // -1 => value; -2 => key; -3 => table
+                       lua_pushvalue(state, -2); // -1 => key; -2 => value; -3 => key; -4 => table
+
+                       const Key key = luwra::read(state, -1);
+                       const bool interrupt = !callback(state, key, -2);
+
+                       lua_pop(state, 2); // -1 => key; -2 => table
+
+                       if (interrupt) {
+                               lua_pop(state, 1);
+                               break;
+                       }
+               }
+               // -1 => table
+               lua_pop(state, 1);
+       }
 };
 
 /// Enables reading/pushing tables
```

So instead of `Table::size()`, another `Table::get()` and another `Table::has()` i added `Table::forEach()` which takes a callback that is being called on every table key taking state, key and value index. I'm able to check value type inside callback and do other stuff i need to do with usual `lua_*` functions and `luwra::` calls.

I still think that `Table::has()` could take into account type, but this `forEach()` seems to be pretty minimal solution, although i'm not sure how pretty this is.

Sorry for a lot of patches, i'm not really expert in luwra, just looking for C++ wrapper for Lua and i like your design. If any of the options looks like a way forward, i can adjust it to whatever suggestions you have and create a PR. I'm not really interested in maintaining my own fork of luwra with any sizable difference, so resolving this in one way or another in upstream would be preferable.

**Comment by vapourismo** [comment]
I think iterating over a table is ambiguous given that Lua tables can be both maps/dictionaries or lists/arrays/vectors. 
Presumably in most cases when one wants to traverse a list, you are interested in treating the table as an array. 

I suggest you stick to the common C++ iterator pattern: support `cbegin()` and `cend()` methods on `Table`. See [here](https://en.cppreference.com/w/cpp/named_req/Container).

Something that is compatible with [this](https://en.cppreference.com/w/cpp/language/range-for) is desirable.

**Comment by vapourismo** [comment]
To clarify: any solution that works with range-based for loops is fine by me.

**Comment by alekseyt** [comment]
Hmm. I don't know about range-based loop. Normally `operator*` returns a reference, but in this case references are stored in Lua, so `operator*` would need to  return reference in Lua by value in C++, or rather a pair of references to table's key and value. 

```c++
std::pair<Reference, Reference>
```

Obvious pitfall is that typical use-case like:

```c++
for (const auto &rec : table) {
  const luwra::Reference &key_ref = rec.first;
  const luwra::Reference &value_ref = rec.second;
}
```

Wouldn't really work because `rec` is a reference to temporary. But assuming this pitfall is fixable, so i now have `key_ref` and `value_ref`, both are `luwra::Reference`, both are currently on stack, however their index mutated when it was transferred to `luwra::RefLifecycle` and it's not `-2` and `-1` anymore.

1. How do i check if `value_ref` has required type?
2. How do i read `key_ref` into string?

For 1 i would want to do something like

```c++
if (lua_isstring(L, value_ref.life->ref) || lua_isnumber(L, value_ref.life->ref)) {}
```

But this doesn't work. Then for 2 i would want to do 

```c++
const std::string key = luwra::read(L, key_ref.life->ref);
```

Which doesn't work either. If i read directly from stack like this:

```c++
if (lua_isstring(L, -1) || lua_isnumber(L, -1)) {}
```

and

```c++
const std::string key = luwra::read(L, -2);
```

Then this works as expected.

I'm kind of lost here, could you point me into the right direction, what am i doing wrong? Does that make sense to store original index in stack reference or should `operator*` return pair of `Value<Reference>` or something, or even `std::pair<int, int>` because references are on stack?

I think i can also push `key_ref.life->ref` to stack and then read, but this looks like an overkill, reference is already on stack when iterator is live. So what do i do to check and read such reference?

**Comment by alekseyt** [comment]
Pushing references to stack actually makes sense because reading might change referenced objects and it does work, but it leads to a strange code like this:

```c++
for (const auto rec : table) {
	const luwra::Reference &key_ref = rec.first;
	const luwra::Reference &value_ref = rec.second;

	luwra::push(L, value_ref);
	if (lua_isnumber(L, -1) == 0 && lua_isstring(L, -1) == 0) {
		lua_pop(L, 1);
		continue;
	}

	const std::string value = luwra::read(L, -1);

	luwra::push(L, key_ref);
	const std::string key = luwra::read(L, -1);

	lua_pop(L, 2);
}
```

If anything, i would rather hide this inside iterator and return reference copies, but then the same problem appears: how to access references (copies) on stack directly through Luwra interface without pushing them to stack again?

**Comment by vapourismo** [comment]
Why are the key and value of your iterator references? It shouldn't be a pair either.
Instead a single [TableAccessorPath](http://luwra.vprsm.de/reference/namespaceluwra_1_1internal.html#aafa888bd5f98c8086f85d71e2481954d) in the same way it is returned from [access](http://luwra.vprsm.de/reference/structluwra_1_1Table.html#a5b97570b735a523da9e0e9ccba5be8d9) (where `key ~ luwra::Integer`).

**Comment by alekseyt** [comment]
Maybe i'm missing something here, but in table like this:

```lua
> x = { "abc", "cba", a = 3 }
> for key, value in pairs(x) do print(key .. " " .. value) end;
1 abc
2 cba
a 3
```

Key can't have fixed type, it may be either string or integer and types are not interchangeable:

```lua
> print(x["1"]);
nil
> print(x[1]);
abc
```

But `TableAccessorPath` takes `Key` as template argument, so supposedly it will be fixed for the duration of loop, no? What am i missing? I though loop has to know return value type of `operator*` beforehand, or am i missing something obvious?

**Comment by alekseyt** [comment]
To be more clear, i see how such iterator will be able to traverse a table like this:

```lua
{ "abc", "bca" }
```

where keys are integer, but in table like this:

```lua
{ a = 3, b = 4 }
```

keys are strings, aren't they? How range-based loop is going to deduce what type of keys i want to iterate over in a code like this:

```c++
for (const auto &rec : table) {}
```

I guess it is possible to make iterator templated with some default key type, but then how do i access key value inside loop, it appears to me that `TableAccessor::read()` or rather `Path::read()` returns a value. It pushes reference to table, then pushes reference to key, then pushes value on stack and reads it, is it not? Is it normal to go with `TableAccessor.accessor.key` to access key reference?

What am i missing?

**Comment by alekseyt** [comment]
If i'm not missing anything, then such iterator won't do what i want it to do anyway. I've looked into how sol3 works with tables and their iterator returns a reference to `std::pair<object, object>` stored inside iterator which makes a lot of sense.

Nevermind. I think i'll go with plain C Lua API with `table_for_each()` in C++. I realized that i've spent 20 minutes implementing `forEach()` and half a day trying to jam it into range-based loop, taking into account that with such iterator it's harder to inspect key and value on application level, i don't think Luwra would benefit from this.

I still think your design is the best among the C++ Lua wrappers that i saw, you've made the right choice when you've built it around raw Lua state instead of introducing layers on top of layers. Because of that it integrates really well into existing code, i'll borrow this design.

I'm going to close both issues because they are no longer relevant. Thank you for looking into this.

**Comment by vapourismo** [comment]
I think a range-based iterator can still work, although not as fast. Or maybe it is enough to convert tables to a `std::map<Key, Value>`.

I will give it a shot over the weekend, if I have some spare time.

With that I would like this ticket to be open so I have a reminder :)

**Comment by vapourismo** [comment]
With 0a29fb750f1a1d24481540d61ffd53342d51adc8 you can extract `std::map<K, V>` from the stack. This allows you to iterate over tables flexibly. For an example, check the diff for [examples/tables.cpp](https://github.com/vapourismo/luwra/commit/0a29fb750f1a1d24481540d61ffd53342d51adc8#diff-73dfcabba7484fe171dedb0a99775908).

**Comment by alekseyt** [comment]
Sorry, i don't quite get the example. To me it seems that it is using the fact that executed script created a variable named `t2` and then access that variable by name: `state["t2"]`.

What if i called a Lua function, this function returned a table, table is on stack at index `-1` (as returned value usually is), now i want to iterate over that table and copy content to C++ structures. Can i do that without creating additional variables in Lua interpreter?

I believe i can read the table like this:

```c++
const luwra::Table table = luwra::read(L, -1);
```

But, looking at source code, i think either `operator[]` or `access()` has to be called on table, both take a key as argument.

**Comment by alekseyt** [comment]
OK, i figured it out:

```c++
const std::map<std::string, luwra::Reference> ret = luwra::read(L, -1);
```

does the trick for table like `{ a = 1, b = 2 }`. However for table like `{ { a =  1, b = 2} } ` Lua aborts in `lua_next()`, it has to be 

```c++
const std::map<int, luwra::Reference> ret = luwra::read(L, -1);
```
(note `std::string` changed to `int`).

I think it aborts because key changes during iteration, it is integer originally, but then it is being read as a string. 

All of this makes sense, please give me some time to digest and test this more deeply.

**Comment by vapourismo** [comment]
`{ { a = 1, b = 2} }` is equivalent to `{ [1] = { a = 1, b = 2 } }`. This means the type of the keys in the outer table is now a number. That's why Lua reports the type error because it is indeed one when you try to extract numbers as strings.

**Comment by alekseyt** [comment]
I think what is happening during `std::map<std::string, luwra::Reference>` reading is:

1. Table and `nil` are pushed to stack, then `lua_next()` is called - this works as expected
2. Key is being read as a string and it actually extracts the key as `"1"` (string containing number `1`). 

So `ret` now contains a record with key `"1"` and reference to value.

3. It pops the value and loops back to `lua_next()`

This is where Lua aborts.

I believe the problem is that key was transformed to string during reading and `lua_next()` aborts because there is no such key (string `"1"`) in table. Seemingly this is the same issue that is described here: https://stackoverflow.com/questions/6137684/iterate-through-lua-table . Specifically this part:

>ensure the original key is left on the stack before the next call to lua_next. luaL_checkstring will convert non-string keys to strings (as the resulting string is not in the table, it becomes an invalid key.) This is most easily done by passing luaL_checkstring a copy of the key instead of the original.

Luwra is using `luaL_checklstring()` to validate the type and documentation seems to also agree on that: https://pgl.yoyo.org/luai/i/luaL_checklstring

> Checks whether the function argument narg is a string and returns this string; if l is not NULL fills *l with the string's length.
>
>This function uses lua_tolstring to get its result, so all conversions and caveats of that function apply here.

Documentation for `luaL_checkstring()` has the very same comment: https://pgl.yoyo.org/luai/i/luaL_checkstring

So here is the patch:

```diff
--- a/3rdparty/luwra/lib/luwra/types/stl.hpp
+++ b/3rdparty/luwra/lib/luwra/types/stl.hpp
@@ -63,10 +63,12 @@ struct Value<std::map<Key, Type>> {
 
                lua_pushnil(state);
                while (lua_next(state, -2) != 0) {
-                       ret.insert(std::make_pair(luwra::read<Key>(state, -2), luwra::read<Type>(state, -1)));
+                       lua_pushvalue(state, -2); // Copy key
 
-                       // Only remove the value, leave the key.
-                       lua_pop(state, 1);
+                       ret.insert(std::make_pair(luwra::read<Key>(state, -1), luwra::read<Type>(state, -2)));
+
+                       // Remove key copy, remove value, leave original key
+                       lua_pop(state, 2);
                }
 
                // Remove the reference to the table that we pushed first.
```

Now it is used with `std::map<std::string, luwra::Reference>`, it will extract keys as strings `"1"`, `"2"` and so on. I think it should also work with mixed tables like `{ { a = 3 }, "abc" }` but i didn't check. I didn't test this patch very well, but it seems to work on my end.

Besides this gotcha with integer keys, i was able to do everything i wanted to do using this tables extraction method and i was also able to check types before reading values (#15).

**Comment by vapourismo** [comment]
I have fixed this in the `Value` specializations for numbers, integers and strings in dcc9b5c. This should prevent further unexpected behavior.

**Comment by alekseyt** [comment]
Works like a charm. Thank you very much.
