### ISSUE TITLE
Custom type metatables replacing each other

### ISSUE THREAD

**Issue by jonmortiboy** [vapourismo/luwra#16]
I'm experiencing an issue when binding multiple user types. Digging through luwra it seems that the metatables are named using a stringified address of a static const int in UserTypeReg. It would seem that building in Release on Visual Studio 2019 results in some optimisation that causes those ints to end up with the same address, which in turn causes all metatables to have the same name and thus each user type that gets bound replaces the metatable of all the other user types.

Replacing the following lines in usertypes.hpp:
```
template <typename UserType>
	const std::string UserTypeReg<UserType>::name =
		LUWRA_REGISTRY_PREFIX + std::to_string(uintptr_t(&id));
```
to instead use the address of _name_ appears to fix the problem:
```
template <typename UserType>
	const std::string UserTypeReg<UserType>::name =
		LUWRA_REGISTRY_PREFIX + std::to_string(uintptr_t(&name));
```
although due to the nature of the issue I'm unsure if this is a suitable fix for other compilers.

**Comment by vapourismo** [comment]
That's a neat solution. Can you write a test for that and package it with the fix into a pull-request?

**Comment by jonmortiboy** [comment]
Sure, thanks for the quick reply. I've just made a pull-request with the above fix and an additional test.
