### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by ZaWarudo111** [vapourismo/luwra#18]
When im trying to compile with Lua 5.3.0, i get this error
![error](https://user-images.githubusercontent.com/79928133/150152226-6c6caab5-37f5-45d2-bf3f-ececced3cd58.png)

**Comment by vapourismo** [comment]
I can't help you if this is all the information you give me. None of the errors even mention this project, so I don't even know if it is the issue.

**Comment by vapourismo** [comment]
Also, this seems to be a linkage error. This library is header-only - there is nothing to be linked.

**Comment by ZaWarudo111** [comment]
I'm using Visual Studio 2019 and Debug/Release will give the same error

**Comment by vapourismo** [comment]
And what exactly are you trying to do?

This library is header-only, it can't be compiled on its own. Which means if you're likely including it in another project that defines multiple `main` methods - hence the error. Luwra does not define that symbol at all. Please check your code on that.

**Comment by ZaWarudo111** [comment]
I was using examples/functions.cpp
