### ISSUE TITLE
Internal errors when trying to register a noexcept member function

### ISSUE THREAD

**Issue by Familex** [vapourismo/luwra#19]
Compile with msvc 17.6.4
Get this errors
|code|description|file|line|
|-|-|-|-|
|C2298|missing call to bound pointer to member function|...\lib\luwra\wrappers.hpp|159|
|C2298|missing call to bound pointer to member function|...\lib\luwra\wrappers.hpp|162|
|C2672|'push': no matching overloaded function found|...\lib\luwra\wrappers.hpp|162|	

## Minimal example
main.cpp:
```cpp
#include "luwra.hpp"

struct Test
{
    void test() noexcept { }
};

int main()
{
    luwra::StateWrapper state;

    state.registerUserType<Test>(
        {
            //
            LUWRA_MEMBER(Test, test)
            //
        },
        {}
    );
}
```

CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 3.8)

project ( luwra_issue )

add_executable(
    luwra_issue
    "src/main.cpp"
)

set_property( TARGET luwra_issue PROPERTY CXX_STANDARD 17 )

# from https://github.com/Crascit/DownloadProject.git
include (download_project/DownloadProject.cmake)

# lua lib; not tested with other versions
download_project (
    PROJ lua_cmake
    GIT_REPOSITORY https://github.com/walterschell/Lua.git
    GIT_TAG master
    UPDATE_DISCONNECTED 1
)
add_subdirectory (${lua_cmake_SOURCE_DIR} ${lua_cmake_BINARY_DIR})
include_directories ("${lua_cmake_SOURCE_DIR}/lua-5.4.6/src")

# luwra (header-only)
download_project (
    PROJ luwra
    GIT_REPOSITORY https://github.com/vapourismo/luwra.git
    GIT_TAG master
    UPDATE_DISCONNECTED 1
)
include_directories ("${luwra_SOURCE_DIR}/lib")

target_link_libraries (
    luwra_issue
    lua_static
)
```

all fine without noexcept, but it looks like a bug 😢

**Comment by vapourismo** [comment]
Are you using a C++11 compliant compiler? Have you tried G++ or Clang?

**Comment by Familex** [comment]
I used only msvc

**Comment by vapourismo** [comment]
Would you be able to try with G++ or Clang in order to verify if this is a shortcoming of MSVC?

**Comment by Familex** [comment]
I downloaded clang via visual studio installer

```
>> .\clang++.exe --version
clang version 15.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix
```

set `CMAKE_C_COMPILER` to `clang.exe` and `CMAKE_CXX_COMPILER` to `clang++.exe`

And provided example gives me this errors:

|code|description|file|line|
|----|-----------|----|----|
|G812C3EF1|pasting formed '::test', an invalid preprocessing token [-Winvalid-token-paste]|...\src\main.cpp|15|
|G812C3EF1|pasting formed '::test', an invalid preprocessing token [-Winvalid-token-paste]|...\src\main.cpp|15|
|G6C92E32D|reference to non-static member function must be called; did you mean to call it with no arguments?|...\lib\luwra\wrappers.hpp|159|
|GD310201E|expression is not assignable|...\lib\luwra\wrappers.hpp|159|	
|G9F5BEB02|static_cast between pointer-to-function and pointer-to-object is a Microsoft extension [-Wmicrosoft-cast]|...\lib\luwra\usertypes.hpp|47|

If I manually expand LUWRA_MEMBER macro to 

```cpp
    state.registerUserType<Test>(
        {
            //
            { "test", (&luwra::internal::MemberWrapper<decltype(&Test::test), Test>::template invoke<&Test::test>)}
            //
        },
        {}
    );
```
then first two errors go away

|code|description|file|line|
|----|-----------|----|----|
|G6C92E32D|reference to non-static member function must be called; did you mean to call it with no arguments?|...\lib\luwra\wrappers.hpp|159|
|GD310201E|expression is not assignable|...\lib\luwra\wrappers.hpp|159|	
|G9F5BEB02|static_cast between pointer-to-function and pointer-to-object is a Microsoft extension [-Wmicrosoft-cast]|...\lib\luwra\usertypes.hpp|47|

But this main.cpp

#include "luwra.hpp"

struct Test
{
    void test() { }
};

int main()
{
    luwra::StateWrapper state;

    state.registerUserType<Test>(
        {
            //
            { "test", (&luwra::internal::MemberWrapper<decltype(&Test::test), Test>::template invoke<&Test::test>)}
            //
        },
        {}
    );
}

**Comment by Familex** [comment]
I missclicked 😅

**Comment by Familex** [comment]
With this g++ all fine

```
>> g++.exe --version
g++.exe (MinGW.org GCC-6.3.0-1) 6.3.0
```

**Comment by vapourismo** [comment]
Unfortunately I can't reproduce this on my end. CI also seems to not care about the `noexcept` annotation: https://github.com/vapourismo/luwra/actions/runs/5567525500.

I suspect this is some Microsoft-specific incompatibility. Messages like `static_cast between pointer-to-function and pointer-to-object is a Microsoft extension [-Wmicrosoft-cast]` seem very suspicious.

However, I think the underlying issue is that the `noexcept` qualifier causes the substitution failure when trying to access whether `test` is a method or field. I'll see if I can extend that in the templates, but I don't know how compatible that is.

**Comment by vapourismo** [comment]
Ok, I did a bit of reading. `noexcept` as part of the function pointer type is a C++17 thing. 

Could you try this patch: https://github.com/vapourismo/luwra/commit/6f371338dcdbc3a80fb3c1cdfe0fddd2b7435f8a

Hopefully that should work with respect to the `noexcept` matching.

**Comment by Familex** [comment]
Cool, what solved my problem

**Comment by vapourismo** [comment]
I've added this upstream in e0e4b6bedd4601310124badc8d2a96b9bad76782.
