### ISSUE TITLE
How to call a Lua function from C++ using Luwra ?

### ISSUE THREAD

**Issue by paly2** [vapourismo/luwra#6]
Sorry,
I've just a question: how to call a Lua function, which is passed as parameter to a C++ function accessible from lua (and wrapped to lua_CFunction using LUWRA_WRAP) ?

For example:
```c++
#include "luwra.hpp"

void test_function(/* What should I write here ? */) {
    /* What should I write here to execute the function passed as parameter ? */
}
int main() {
    luwra::StateWrapper state;
    state.loadStandardLibrary();
    state["test_function"] = LUWRA_WRAP(test_function);
    state.runString("test_function(function() print('Hello world!') end)");
    return 0;
}
```

**Comment by vapourismo** [comment]
```c++
void test_function(luwra::NativeFunction<R> func) {
    R ret = func(1, 2, 3, "Hello Worldd");
}
```

`R` is the type which the Lua function returns.

**Comment by paly2** [comment]
I tried this, but it didn't compile :

```
./luwra/functions.hpp:77:20: error: no matching function for call to 'push'
                size_t numArgs = push(impl->state, std::forward<A>(args)...);
                                 ^~~~
./luwra/types.hpp:74:8: note: candidate function template not viable: requires 2 arguments, but 1 was provided
size_t push(State* state, T value) {
       ^
./luwra/types.hpp:82:8: note: candidate function template not viable: requires at least 3 arguments, but 1 was provided
size_t push(State* state, T1 value, T2&& head, TR&&... rest) {
```

**Comment by vapourismo** [comment]
Please post the code.

**Comment by paly2** [comment]
Here's the file where the error happens (line 14): http://pastebin.ubuntu.com/16461588/

**Comment by vapourismo** [comment]
It is fixed in 144b7bc53d3e8e4ec8814b24b2ecd059998a0bb0. Apparently variadic template parameters cannot match against 0 parameters.

**Comment by paly2** [comment]
It works now, thank you !

**Comment by paly2** [comment]
Sorry to reopen this issue,
Is there a way to obtain a `std::function` from a `luwra::NativeFunction` ?

**Comment by vapourismo** [comment]
Yes. You don't need Luwra for that.

```c++
luwra::NativeFunction<int> foo =
    state.get<luwra::NativeFunction<int>>("my_function_3");

std::function<int(int, int)> f_foo = [foo](int a, int b) -> int {
    return foo(a, b);
};
```

If you're not running with the latest version, you might need to capture `foo` my reference.

**Comment by paly2** [comment]
I didn't think about something like that (utilisation of lambdas), but you're absolutely right, I can do that !

**Comment by vapourismo** [comment]
I just looked over the C++ spec and if I am not mistaken, this code might work aswell:

```c++
luwra::NativeFunction<int> foo = /* magic */;
std::function<int(int, int)> f_foo(foo);
```

**Comment by paly2** [comment]
Yes it does, you're write, because the `luwra::NativeFunction` is a callable object
